Update integration ci
rancher/webhook pull request #213
Opened 2023-04-05 12:29 UTC by KevinJoiner

Added the startup probe to the rancher-webhook chart so that the Webhook does not appear to be ready before it has updated the validating webhook configuration.
The startup probe checks every 5 seconds for 10 minutes before declaring that the webhook failed to start.
These values seemed reasonable to me but are up for discussion. `5s periodSeconds * 120 failureThreshold`

In the second commit, I updated the integration test to install the newly packaged charts created in CI to provide us with a larger test coverage. I also added a command that will start tailing the rancher logs if Rancher-Webhook fails to deploy after 5 minutes.

2023-04-05 23:02 UTC, rmweir requested changes
10 minutes seems excessive to me. I think 5 should be enough. If that doesn't sound right to you and other reviewers though then 10 is fine. It's difficult to reason about what to set it to apart from limited experience watching it.

2023-04-20 12:49 UTC, KevinJoiner commented
It's probably also worth adding a liveness probe to the deployment with the same endpoint.

2023-04-27 17:26 UTC, rmweir approved these changes

2023-04-28 14:38 UTC, MbolotSuse reviewed
A couple of small nits and one minor concern, but I think the overall approach is good.

2023-04-28 17:16 UTC, KevinJoiner commented on charts/rancher-webhook/templates/deployment.yaml
> +          successThreshold: 1
Updated.

2023-04-28 17:16 UTC, KevinJoiner commented on charts/rancher-webhook/templates/deployment.yaml
> +          timeoutSeconds: 1
Updated.

2023-04-28 17:16 UTC, KevinJoiner commented on scripts/integration-test
> +helm upgrade rancher-webhook ./dist/artifacts/rancher-webhook-${HELM_VERSION}.tgz -n cattle-system --set image.repository=${WEBHOOK_REPO} --set image.tag=${TAG}
Updated.

2023-04-28 18:37 UTC, MbolotSuse approved these changes

2023-05-02 15:16 UTC, rmweir approved these changes

2023-05-03 16:04 UTC, merged