[v0.5] s4: Fixes 227
rancher/webhook pull request #404
Opened 2024-06-17 14:25 UTC by pmatseykanets

## Issue: 

Port of #390

## Problem

## Solution

## CheckList
  
- [ ] Test
  
- [ ] Docs

2024-06-17 18:35 UTC, ericpromislow requested changes
The PR fails because the drone config uses `rancher/rancher:v2.9-head` and that image quietly changed its base image from `registry.suse.com/bci-base` to `bci-micro`, and the latter doesn't include `zypper` .

I fixed this on other PRs that still use drone by moving it back to `v2.9.0-alpha1`

2024-06-17 19:33 UTC, pmatseykanets commented
@ericpromislow Thanks for the insights! It seems like the required change is not related to this port in any way and should be applied is a separate PR. Then this one can be rebased.

2024-06-17 20:28 UTC, pmatseykanets commented
Depends on and needs to be rebased off of #406

2024-06-17 22:17 UTC, JonCrowther approved these changes

2024-06-18 07:35 UTC, raulcabello approved these changes

2024-06-18 07:37 UTC, andreas-kupries commented on pkg/resources/management.cattle.io/v3/setting/Setting.md
> +- If set, `delete-inactive-user-after` must be zero or a positive duration (e.g. `240h`).
The `MinDeleteInactiveUserAfter` check does not seem to be documented. Is that intentional ?

2024-06-18 11:26 UTC, merged