[v0.4] Set FailurePolicy to Ignore for settings validator
rancher/webhook pull request #447
Opened 2024-07-10 20:19 UTC by pmatseykanets

## Issue: 

Backport of #446

## Problem

## Solution

## CheckList
  
- [ ] Test
  
- [ ] Docs

2024-07-10 20:32 UTC, tomleb approved these changes

2024-07-10 21:00 UTC, maxsokolovsky submitted a review, later dismissed

2024-07-10 21:02 UTC, MbolotSuse requested changes
Blocking merge until we decide on milestone.

2024-08-01 17:33 UTC, MbolotSuse approved these changes
LGTM please squash when merging.

2024-08-01 19:38 UTC, ericpromislow approved these changes
LG. Same code and test sequence as PR 446.

2024-08-01 19:40 UTC, merged