Prevent deletion of `local` cluster
rancher/webhook pull request #551
Opened 2024-12-05 12:59 UTC by dharmit

## Issue: 

https://github.com/rancher/rancher/issues/32745

## Problem

Presently, it's possible to delete the `local` cluster using:
```sh
$ k delete cluster.management.cattle.io local
```

## Solution

Update the validating webhook to prevent the deletion.

## CheckList
  
- [ ] Test
  
- [ ] Docs

2024-12-06 23:39 UTC, ericpromislow submitted a review, later dismissed
Given that `"local"` already appears in that file, I would set it to a constant called `localCluster`, like in `pkg/resolvers/grbRuleResolvers.go`

2024-12-31 08:51 UTC, jakefhyde requested changes

2024-12-31 08:51 UTC, jakefhyde commented on pkg/resources/management.cattle.io/v3/node/validator.go
> +	if request.Operation == admissionv1.Delete && oldNode.Namespace == localNs {
What if a user rotates all of the nodes in their local cluster? I don't think we should be leaving all of the nodes that have ever existed around. If they rotate nodes say once a month, after a year you could have 96 left over node objects. Rotate enough nodes, and you could have resource exhaustion in the local cluster. I would recommend updating the approach to maybe account for accidental deletion, but allow intentional deletion. i.e. if the corev1.Node object really doesn't exist anymore, then perhaps annotate the v3.Node object and gate the deletion validator behind the presence of the annotation for the local cluster.

2025-01-02 13:19 UTC, dharmit commented on pkg/resources/management.cattle.io/v3/node/validator.go
> +	if request.Operation == admissionv1.Delete && oldNode.Namespace == localNs {
Thanks for the review, @jakefhyde. Your observation is spot on and something I hadn't thought of. If I delete a v1.Node, the change proposed in this PR keeps preventing the deletion of corresponding v3.Node object indefinitely.

In terms of the solution to this problem, are you suggesting annotating the v3.Node when its corresponding v1.Node is deleted, and if a v3.Node with the said annotation is marked for deletion, the webhook should let that through? If yes, this change would go into the rancher code, right? I'm trying to find and understand the relevant code bits for this. I think the file we're interested in is `pkg/controllers/management/node/controller.go`, but let me know if you have any pointers.

2025-01-03 15:57 UTC, jakefhyde commented on pkg/resources/management.cattle.io/v3/node/validator.go
> +	if request.Operation == admissionv1.Delete && oldNode.Namespace == localNs {
This is where we delete the machine if the downstream node no longer exists: https://github.com/rancher/rancher/blob/b435a2d786c50b03bd1ba7279a6a621ebcd19c84/pkg/controllers/managementuser/nodesyncer/nodessyncer.go#L496. Can I ask why we want to prevent deleting the machine? Reading https://github.com/rancher/rancher/issues/48303:
> At a glance it seems that the issue happens because deletion of local namespace (naturally) triggers deletion of management.cattle.io.nodes
I feel like if we prevent deletion of the namespace, then we don't need to change how deleting machines works.

2025-01-07 05:46 UTC, dharmit commented on pkg/resources/management.cattle.io/v3/node/validator.go
> +	if request.Operation == admissionv1.Delete && oldNode.Namespace == localNs {
> I feel like if we prevent deletion of the namespace, then we don't need to change how deleting machines works.

Agree. But if the admin directly deletes a node using `kubectl`, that would render the cluster unstable, no? In argument to that, we can always say that an admin should know what they are doing and what its consequences would be.

@snasovich can you chime in on this one?

2025-01-07 21:19 UTC, jakefhyde commented on pkg/resources/management.cattle.io/v3/node/validator.go
> +	if request.Operation == admissionv1.Delete && oldNode.Namespace == localNs {
> Agree. But if the admin directly deletes a node using `kubectl`, that would render the cluster unstable, no?

This would only be a problem if they deleted all of their nodes, not just one. I also think that's somewhat outside the scope of this issue, it seems to me like it's just about preventing the deletion of the local namespace. I think if you incorporate a change to how node objects are deleted on such a short timetable, the regression chance is going to be too high.

2025-01-08 17:34 UTC, jakefhyde requested changes
LGTM, but just wanted to confirm that the agent's `CLUSTER_CLEANUP` is unimpacted.

2025-01-08 17:39 UTC, jakefhyde approved these changes

2025-01-10 11:47 UTC, crobby commented on pkg/resources/core/v1/namespace/projectannotations.go
> +//   - deletion of `local` and `fleet-local` namespace is not allowed as it could
as it could......what?

2025-01-10 16:56 UTC, crobby submitted a review, later dismissed
One small non-blocking nit on a comment, otherwise, lgtm

2025-01-10 17:20 UTC, dharmit commented on pkg/resources/core/v1/namespace/projectannotations.go
> +//   - deletion of `local` and `fleet-local` namespace is not allowed as it could
Lol. 😂 
I thought I had removed those words.

2025-01-10 17:23 UTC, dharmit commented on pkg/resources/core/v1/namespace/projectannotations.go
> +//   - deletion of `local` and `fleet-local` namespace is not allowed as it could
Done. Removed.

2025-01-10 22:24 UTC, jakefhyde approved these changes

2025-01-13 16:18 UTC, crobby approved these changes

2025-01-15 05:28 UTC, merged