[v0.7|main] Make admission rejection message more useful for namespace creation
rancher/webhook pull request #572
Opened 2024-12-17 17:22 UTC by crobby

## Issue: 

https://github.com/rancher/rancher/issues/47585

## Problem

Webhook rejection message was not useful in this situation

## Solution

Include user, verb, resource in the rejection message.

2024-12-19 13:05 UTC, nflynt approved these changes

2025-01-27 19:54 UTC, ericpromislow requested changes
Would be good if there could be a unit test for this. I tried messing with the test file, but always get an actual error "error when creating sar, server unavailable" instead of a fabricated one. Not sure if the underlying function is properly mocked.

Looks fine otherwise.

2025-02-03 16:07 UTC, crobby commented
> Would be good if there could be a unit test for this. I tried messing with the test file, but always get an actual error "error when creating sar, server unavailable" instead of a fabricated one. Not sure if the underlying function is properly mocked.
> 
> Looks fine otherwise.

I've updated an existing test to check the message for this case.

2025-02-03 16:44 UTC, joshmeranda approved these changes

2025-02-05 00:35 UTC, ericpromislow approved these changes
LGTM

2025-02-05 12:17 UTC, merged