Update cert expiration from master
rancher/webhook pull request #67
Opened 2022-01-06 01:51 UTC by genexpr

Related to https://github.com/rancher/rancher/issues/35068.

This back-ports a commit that allows to specify the webhook's certificate expiration date in days and, by default, set the certificate's expiration date to 10 years after creation. This expiration date is passed down to the dynamiclistener via the new `CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS` environment variable.

Once the corresponding [PR](https://github.com/rancher/dynamiclistener/pull/54) for dynamiclistener is merged, I will update webhook's `go.mod` so that it requires `dynamiclistener` at the appropriate commit.

2022-01-06 19:20 UTC, cmurphy reviewed
Looks like another commit is needed to fix the copyright headers for `go generate` https://drone-pr.rancher.io/rancher/webhook/162/1/2

Then once go.mod is updated lgtm

2022-01-07 19:48 UTC, genexpr commented
When this is merged, we will tag this (v0.1.3-rc1). And then update Rancher `release/v2.5` package/Dockerfile to set the `CATTLE_RANCHER_WEBHOOK_MIN_VERSION` to the tag value.

2022-01-07 22:10 UTC, cbron approved these changes

2022-01-07 22:10 UTC, cbron commented on go.mod
> +	github.com/rancher/dynamiclistener v0.2.8-0.20220107182323-a73b7d7f4c0c
We'll need to tag this before 2.5.12 release

2022-01-07 22:20 UTC, cmurphy requested changes
Could you squash 9f9341b798a098f473334e3ceddff6a2bdc7eaab e1e7a6da370d2e2a34c417c3ffb6600e03f1aa4f and 1aed61ccc7a4e217eabe4112096ab841d6f5c800 into a single commit?

2022-01-07 22:37 UTC, cmurphy approved these changes

2022-01-07 23:13 UTC, merged