Update CRTB/PRTB validation handlers to disallow RoleTemplate updates
rancher/webhook pull request #78
Opened 2022-03-29 19:57 UTC by ryansann

These changes bring the CRTB and PRTB CRs more in line with the underlying k8s RBAC types, which disallow updates to RoleRef. This also addresses a bug with Apply in Rancher, where a CRTB can't be synced because a RoleBinding is applied with a different RoleRef after the CRTB had it's RoleTemplateName updated

2022-04-11 17:38 UTC, MbolotSuse requested changes

2022-04-11 17:38 UTC, MbolotSuse commented on pkg/resources/validation/clusterroletemplatebinding/clusterrtb.go
> +	if crtb.ClusterName != "local" { // the prtb custom resource only exists in the local cluster
Two Things here:

1. I don't think that the ClusterName in this case refers to the name where the object is in. I think this is the name of the cluster that the binding is in effect for (e.x. user y has access to role rt in cluster x -> in this case, x is the ClusterName). Do we really want to have a short circut in here? I kind of think that this should be removed.
2. Nit: this file is for crtbs, but the comment references prtbs. I recommend revising this.

2022-04-11 17:38 UTC, MbolotSuse commented on pkg/resources/validation/projectroletemplatebinding/projectrtb.go
> +	if clusterID != "local" { // the crtb custom resource only exists in the local cluster
Similar comment here as on the above (comment refers to crtbs but this file is for prtbs, and the cluster ID refers to the cluster that the permissions are effective for). Leaving this comment so we have a note here, but let's reserve discussion for the above comment.

2022-04-13 16:07 UTC, MbolotSuse approved these changes
LGTM

2022-04-15 17:39 UTC, rmweir approved these changes
LGTM

2022-04-18 17:02 UTC, merged